INSERT INTO raw.blocks
SELECT
    timestamp,
    number,
    base_fee_per_gas AS baseFeePerGas,
    difficulty,
    extra_data AS extraData,
    gas_limit AS gasLimit,
    gas_used AS gasUsed,
    hash,
    logs_bloom AS logsBloom,
    miner,
    mix_hash AS mixHash,
    nonce,
    parent_hash AS parentHash,
    receipts_root AS receiptsRoot,
    sha3_uncles AS sha3Uncles,
    size,
    state_root AS stateRoot,
    total_difficulty AS totalDifficulty,
    transactions_root AS transactionsRoot,
    uncles